language: sh
sudo: required

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y yash dash pdksh ksh

before_script:
    - curl -L "https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz" | tar zx

script:
    - sh unit_test.sh
    - sh sh_integration_test.sh
